import { ElementRef, KeyValueDiffers, EventEmitter, ChangeDetectorRef, DoCheck, Renderer2, OnDestroy } from '@angular/core';
import { ActivateHelperService, ScrollbarHelper } from '../../services';
import { TableActivateEvent, TreeStatus } from '../../index';
export declare class DataTableBodyRowComponent implements DoCheck, OnDestroy {
    private differs;
    private scrollbarHelper;
    private cd;
    private activateEventHelper;
    private renderer;
    columns: any[];
    innerWidth: number;
    expanded: boolean;
    rowClass: any;
    row: any;
    group: any;
    isSelected: boolean;
    rowIndex: number;
    displayCheck: any;
    treeStatus: TreeStatus;
    offsetX: number;
    readonly cssClass: string;
    rowHeight: number;
    readonly columnsTotalWidths: string;
    activate: EventEmitter<TableActivateEvent>;
    treeAction: EventEmitter<any>;
    _element: any;
    _columnGroupWidths: any;
    _columnsByPin: any;
    _offsetX: number;
    _columns: any[];
    _innerWidth: number;
    _groupStyles: {
        [prop: string]: {};
    };
    private _rowDiffer;
    private _listeners;
    constructor(differs: KeyValueDiffers, scrollbarHelper: ScrollbarHelper, cd: ChangeDetectorRef, element: ElementRef, activateEventHelper: ActivateHelperService, renderer: Renderer2);
    ngDoCheck(): void;
    ngOnDestroy(): void;
    trackByGroups(index: number, colGroup: any): any;
    columnTrackingFn(index: number, column: any): any;
    buildStylesByGroup(): void;
    calcStylesByGroup(group: string): {
        width: string;
    };
    onActivate(event: TableActivateEvent, index: number): void;
    recalculateColumns(val?: any[]): void;
    onTreeAction(): void;
    private registerEvents;
}
